export const products = [
    {
        id: 'p1',
        name: 'Striped Men Polo Neck White, Blue, Yellow T-Shirt',
        productImg: 'https://rukminim1.flixcart.com/image/580/696/kzegk280/t-shirt/n/h/l/s-t285hs-as7whdnmt-eyebogler-original-imagbfyge6kae4xg.jpeg',
        brand: 'Eyebogler',
        price: 368,
        sizes: ['s', 'm', 'l'],
        idealFor: ['men'],
    },
    {
        id: 'p2',
        name: 'Solid Men Mandarin Collar Black, Grey T-Shirt',
        productImg: 'https://rukminim1.flixcart.com/image/880/1056/kyrlifk0/t-shirt/0/u/s/l-tdgyblhenful-d37-tripr-original-imagax9x6pkgwwg9.jpeg',
        brand: 'TRIPR',
        price: 332,
        sizes: ['s', 'm', 'xl'],
        idealFor: ['men'],
    },
    {
        id: 'p3',
        name: 'Casual Regular Sleeves Solid Women White Top',
        productImg: 'https://rukminim1.flixcart.com/image/580/696/ke1pnrk0/top/f/d/f/s-tttp003830-tokyo-talkies-original-imafutjs8cxxzg2z.jpeg',
        brand: 'Tokyo Talkies',
        price: 329,
        sizes: ['s', 'l', 'xl'],
        idealFor: ['women'],
    },
    {
        id: 'p4',
        name: 'Color Block Men Round Neck Black, Grey T-Shirt',
        productImg: 'https://rukminim1.flixcart.com/image/880/1056/kuvkcy80/sweatshirt/o/d/g/14-15-years-100l-skylink-original-imag7wghm7tywcwq.jpeg',
        brand: 'Try This',
        price: 238,
        sizes: ['m', 'l', 'xl'],
        idealFor: ['men'],
    },
    {
        id: 'p5',
        name: 'Women A-line Multicolor Dress',
        productImg: 'https://rukminim1.flixcart.com/image/880/1056/k2tc1ow0pkrrdj/dress/2/6/d/s-dark-blue-pink-beige-multicolor-79tkj2253-siril-original-imafhnehpyryvxc4.jpeg',
        brand: 'Dhyani Enterprise',
        price: 285,
        sizes: ['s', 'm', 'l', 'xl'],
        idealFor: ['women'],
    },
    {
        id: 'p6',
        name: 'Printed Unisex Round Neck Black T-Shirt',
        productImg: 'https://rukminim1.flixcart.com/image/880/1056/kelptow0-0/t-shirt/k/s/f/m-friends-printcorners-original-imafv8u4saxssjmb.jpeg',
        brand: 'print corners',
        price: 329,
        sizes: ['s', 'm', 'l', 'xl'],
        idealFor: ['men', 'women'],
    },
]